streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': [user/themes/local, user/themes/minimal, user/themes/quark-open-publishing, user/themes/quark]
chromeless:
  enabled: false
display_of_git_sync_repo_link: none
type_of_git_sync_repo_link: view
h5pembedrootpath: 'https://h5p.org/h5p/embed/'
displaycustommenus:
  enabled: false
hidehomemenulink: true
production-mode: true
header-fixed: true
header-animated: true
header-dark: true
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
grid-size: grid-xl
menu:
  -
    text: Grav
    icon: arrow-circle-right
    url: 'https://getgrav.org/'
    target: _blank
dropdown:
  enabled: true
blog_page_hero_classes: 'text-light title-h1h2 overlay-dark-gradient hero-large parallax'
favicon:
  user/themes/local/images/favicon.svg:
    name: favicon.svg
    full_path: favicon.svg
    type: image/svg+xml
    size: 21997
    path: user/themes/local/images/favicon.svg
custom_logo:
  user/themes/local/images/logo/crabston-white.svg:
    name: crabston-white.svg
    full_path: crabston-white.svg
    type: image/svg+xml
    size: 20688
    path: user/themes/local/images/logo/crabston-white.svg
custom_logo_mobile:
  user/themes/local/images/logo/crabston.svg:
    name: crabston.svg
    full_path: crabston.svg
    type: image/svg+xml
    size: 21997
    path: user/themes/local/images/logo/crabston.svg
