title: 'Crabston GmbH'
default_lang: de
author:
  name: 'Crabston GmbH'
  email: contact@crabston.dev
taxonomies:
  - category
  - tag
  - month
  - author
  - filter
metadata:
  description: 'Wir sind Crabston und bieten verschiedene IT Dienstleistungen an.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: '/blog'
