title: Crabston
default_lang: de
author:
  name: Crabston GmbH
  email: kontakt@crabston.ch
taxonomies:
  - category
  - tag
  - month
  - author
  - filter
metadata:
  description: 'Crabston ist ein junges Schweizer Familienunternehmen. Wir bieten verschiedene IT Dienstleistungen, unter anderem Support sowie individuelle IT Lösungen an. Spezialisiert haben wir uns auf die Erstellung von Websites und Webshops, die leicht zu verwalten sind, selbst für Personen ohne Vorkenntnisse.'
  keywords: 'Crabston, IT Dienstleistungen, IT Support, Webentwicklung, Website, Webshop, Online Shop, Webdesign'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: '/blog'
